name: "ensemble"
platform: "ensemble"
max_batch_size: 8
input [
  {
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [1]
  }
]
output [
  {
    name: "EMBEDDING_ONNX"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "EMBEDDING_TRT_FP16"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "EMBEDDING_TRT_FP32"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "EMBEDDING_TRT_INT8"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "EMBEDDING_TRT_BEST"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]
instance_group [
  {
    kind: KIND_GPU
  }
]
